### ISSUE TITLE
What type of policy is being trained using the MoCapact dataset?

### ISSUE THREAD

**Issue by Rakesh-Paul01** [carlosferrazza/BodyTransformer#2]
Hi I saw the project page and noted that you used BC to train the policy. Could you confirm what type of policy it was, like was it a multiclip policy (a generalized model for all clips) or was it an expert policy (each policy for each motion file)?

**Comment by carlosferrazza** [comment]
Hi! In our BC experiments, we are training a policy for all clips (we use the small MoCapAct dataset).

**Comment by Rakesh-Paul01** [comment]
Thanks for the clarification.
